# Generated by Django 5.2 on 2025-04-29 13:05

from django.db import migrations, models


def extract_username(user):
    """
    Return the username of the user.
    Implemented to return the part of the email before the '@' symbol.
    """
    return user.email.split('@')[0]

def create_organizations_for_existing_users(apps, schema_editor):
    """
    Create a default personal organization for existing users.
    This function is called during the migration to ensure that all existing users
    have at least one organization.
    """
    User = apps.get_model('accounts', 'User')
    Team = apps.get_model('organization', 'Team')

    for user in User.objects.all():
        if user.organizations.count() > 0:
            continue

        username = extract_username(user)
        if not username:
            print(f"User {user.pk} does not have a username. Skipping organization creation.")
            continue

        # Create the personal organization
        organization = Team.objects.create(
            name=f"{username}'s Personal Organization",
            is_organization=True,
        )
        user.organizations.add(organization)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(
                blank=True,
                help_text='The organizations this user is a member of.',
                related_name='members',
                to='organization.team',
            ),
        ),
        migrations.RunPython(create_organizations_for_existing_users),
    ]
