# Generated by Django 5.2 on 2025-05-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr.objective')),
            ],
        ),
    ]
